server:
  port: 9696
spring:
  messages:
    basename: i18n.login
  datasource:
    username: root
    password: E&7D*8C(9
    url: jdbc:mysql://127.0.0.1:3306/zktest?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 2
    min-idle: 2
    max-active: 2
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT   1   FROM    DUAL
    test-on-borrow: FALSE
    test-on-return: FALSE
    test-while-idle: TRUE
    pool-prepared-statements: TRUE
    max-pool-prepared-statement-per-connection-size: 2
    validation-query-timeout: 10
    min-evictable-idle-time-millis: 300000
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    initializationMode: always
#    schema:
#      - classpath: schema-all.sql
debug: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




person:
  id: ${random.int}
  name: ${random.uuid}
  date: 2020/11/23
  map: {k1: v1,k2: v2}
  list:
    - lisi
    - wangwu
  dog:
    name: 小狗
    age: 22
